const columns = {
  events: [
    "event_id",
    "event_revision_id",
    "event_time",
    "source_updated_at",
    "magnitude",
    "magnitude_type",
    "longitude",
    "latitude",
    "depth_km",
    "status",
    "event_type",
    "review_status",
    "place_description",
    "captured_state_count",
    "source_id",
    "licence_id",
  ],
  revisions: [
    "event_id",
    "event_revision_id",
    "captured_state_number",
    "is_initial_state",
    "event_time",
    "source_updated_at",
    "magnitude",
    "magnitude_type",
    "longitude",
    "latitude",
    "depth_km",
    "status",
    "event_type",
    "review_status",
    "place_description",
    "changed_fields",
    "source_id",
    "licence_id",
  ],
  daily_activity: ["activity_date_utc", "event_count", "max_magnitude"],
  places: [
    "place_id",
    "name",
    "place_type",
    "country_code",
    "admin1_code",
    "admin1_name",
    "latitude",
    "longitude",
    "population_context",
    "population_year",
    "population_source_id",
    "source_id",
    "source_vintage",
    "raw_snapshot_sha256",
  ],
};

const artifactDetails = {
  events: ["events/year=2026/events.parquet", "pf1-207-preview-events-v1"],
  revisions: ["revisions/year=2026/revisions.parquet", "pf1-207-preview-revisions-v1"],
  daily_activity: ["activity/daily.parquet", "pf1-207-preview-daily-activity-v1"],
  places: ["places/places.parquet", "places-parquet-v2"],
} as const;

export function makePreviewManifest(): Record<string, unknown> {
  return {
    product_kind: "quakelens-browser-preview",
    preview_schema_version: "1",
    preview_build_id: "20260921T204938Z-a14edef9b000",
    generated_at: "2026-09-21T20:49:38.631441Z",
    included_coverage: {
      event_time_start_inclusive: "2026-01-01T00:00:00Z",
      event_time_end_exclusive: "2026-09-01T00:00:00Z",
      observed_min_event_time: "2026-01-01T00:03:02.325000Z",
      observed_max_event_time: "2026-08-31T23:16:53.463000Z",
      annual_partition: 2026,
      acquisition_status: "complete",
      catalogue_complete: true,
      detail_complete: true,
    },
    excluded_or_incomplete_partitions: [
      {
        event_time_start_inclusive: "2017-01-01T00:00:00Z",
        event_time_end_exclusive: "2026-01-01T00:00:00Z",
        state: "not_published",
        reason: "Outside this preview and not zero activity.",
      },
    ],
    capabilities: {
      events: "available",
      revisions: "captured_history",
      places: "us_census_2024",
      tectonics: "not_in_preview",
      shaking: "not_in_preview",
      exposure: "not_in_preview",
    },
    artifacts: Object.entries(artifactDetails).map(
      ([logicalName, [relativePath, contract]]) => ({
        logical_name: logicalName,
        relative_path: relativePath,
        contract_version: contract,
        rows: 2,
        bytes: 100,
        sha256: "a".repeat(64),
        columns: columns[logicalName as keyof typeof columns].map((name) => ({
          name,
          physical_type: "VARCHAR",
        })),
      }),
    ),
    sources_and_attribution: {
      sources: [
        {
          source_id: "usgs_earthquakes",
          provider: "U.S. Geological Survey",
          attribution: "U.S. Geological Survey (USGS)",
          source_url: "https://earthquake.usgs.gov/data/comcat/",
          licence_id: "usgs-public-domain",
          redistribution_notes: "Retain source credit.",
        },
      ],
      licences: [
        {
          licence_id: "usgs-public-domain",
          name: "USGS public domain",
          licence_url: "https://www.usgs.gov/",
          attribution_requirements: "Acknowledge USGS.",
          redistribution_notes: "Public domain where applicable.",
        },
      ],
    },
  };
}
